In [59]:
l1=[20,30,58,59,68,67]
l1.pop(1)

30

In [60]:
l1

[20, 58, 59, 68, 67]

In [ ]:
set=(1,2,3,4,5,15,6)



In [6]:
tuple1=(20,48,46,68,8)
tuple1

(20, 48, 46, 68, 8)

In [22]:
tuple1[1]=2

TypeError: 'tuple' object does not support item assignment

In [ ]:
#tuple can be replaced by converting to list and we can replace

In [8]:
l1 = [1,2,3,4,15,6]
l1[2]=10
l1

[1, 2, 10, 4, 15, 6]

In [9]:
l1[4]=5

In [10]:
l1

[1, 2, 10, 4, 5, 6]

In [11]:
l1.insert(5,"Hello")

In [12]:
l1

[1, 2, 10, 4, 5, 'Hello', 6]

In [14]:
l1.append('how')

In [15]:
l1

[1, 2, 10, 4, 5, 'Hello', 6, 'how']

In [18]:
l2 = [22,14,8,5,69,75,10]
l2.sort()
l2
      

[5, 8, 10, 14, 22, 69, 75]

In [19]:
l2.sort(reverse = True)

In [20]:
l2

[75, 69, 22, 14, 10, 8, 5]

In [21]:
l1.extend(l2)
l1

[1, 2, 10, 4, 5, 'Hello', 6, 'how', 75, 69, 22, 14, 10, 8, 5]

In [23]:
t1 = (1,2,"giugiuyds" )
t1

(1, 2, 'giugiuyds')

In [24]:
t1[0]

1

In [26]:
t2=list(t1)

In [27]:
t2

[1, 2, 'giugiuyds']

In [28]:
t2[2]=3

In [32]:
t2

[1, 2, 3]

In [40]:
t3 =('hey',)

In [41]:
type(t3)

tuple

In [42]:
tup = (1,2,3,4,5,6,5,4,5,1,1,1,1)

In [57]:
tup.pop()

AttributeError: 'tuple' object has no attribute 'pop'

In [45]:
tup1=tup.count(2)
tup1

1

In [48]:
tup1=tup.index(6)
tup1

5

In [2]:
#set is unordered
s={5,9,4,5,7}
s

{4, 5, 7, 9}

In [3]:
type(s)

set

In [4]:
s.pop()

9

In [ ]:
data = df.drop(["sc_h"],axis = 1,inplace=True)data = df.drop(["sc_h"],axis = 1,inplace=True)

In [66]:
s1={1,2,3,4,5,6}

In [70]:
s1.pop(2)

TypeError: pop() takes no arguments (1 given)

In [68]:
s1.pop()

2

In [69]:
s1.pop()

3

In [1]:
a = {}

In [ ]:
type(a)

In [1]:
#set--we cannot perform slicing
s = {1,2,3,4,5}

In [2]:
s[1]

TypeError: 'set' object is not subscriptable

In [3]:
# Since set is unordered
# Ordered set
!pip install ordered_set

In [4]:
from ordered_set import OrderedSet

In [5]:
s1 = OrderedSet(s)
s1

OrderedSet([1, 2, 3, 4, 5])

In [6]:
type(s1)

ordered_set.OrderedSet

In [7]:
s1[1:3]

OrderedSet([2, 3])

In [8]:
# Conditional Statements --> if-else
# if(condition):
#       task1
# else:
#       task2

In [9]:
a = 10
b = 20
if(a>b):
    print('a is greater')
else:
    print('b is greater')

b is greater


In [10]:
a = 20
b = 20
if(a>b):
    print('a is greater')
elif(a==b):      # else-if --> They are used for working with multiple conditions, after if and before else
    print('Both are equal')
else:
    print('b is greater')

Both are equal


In [12]:
# I want to check whether the number entered by the user is positive, negative or zero
a1 = int(input('Enter a number: '))
if(a1>0):
    print(a1, 'is positive')
elif(a1<0):
    print(a1, 'is negative')
else:
    print('The number is zero')

Enter a number: 0
The number is zero


Print the grade of a student based upon the following terms:

marks>90 --> Grade A

marks>80 and marks<=90 --> Grade B

marks>60 and marks<=80 --> Grade C

marks<60 --> Grade D

In [13]:
n = int(input('Enter the marks: '))
if(n>90):
    print('Grade A')
elif(n>80) & (n<=90):
    print('Grade B')
elif(n>60) & (n<=80):
    print('Grade C')
else:
    print('Grade D')

Enter the marks: 70
Grade C


In [14]:
# Loops --> Performing the same task again and again n number of times
# for loop
# while loop

In [15]:
# for loop --> range()
# range(n) --> n --> range value
# range(5) --> 0,1,2,3,4
# for i in range(n):
#        task
# i --> traversing variable

In [16]:
# I want to print Python 10 no. of times
for i in range(10):
    print('Python', i)

Python 0
Python 1
Python 2
Python 3
Python 4
Python 5
Python 6
Python 7
Python 8
Python 9


In [17]:
# Print the table for the number entered by the user using a for loop
x = int(input('Enter a number: '))
for i in range(1,11):
#     r = x * i
#     print(x, '*', i, '=', r )
    print(x, '*', i, '=', x * i)

Enter a number: 55
55 * 1 = 55
55 * 2 = 110
55 * 3 = 165
55 * 4 = 220
55 * 5 = 275
55 * 6 = 330
55 * 7 = 385
55 * 8 = 440
55 * 9 = 495
55 * 10 = 550


In [18]:
# while loop --> works with conditions

# define the starting value for i
# mention the condition
# mention the task to be performed
# incrementation for i variable

# while(condition):

In [19]:
i = 1
while(i<11):
    print('Python', i)
    i = i+1

Python 1
Python 2
Python 3
Python 4
Python 5
Python 6
Python 7
Python 8
Python 9
Python 10


In [20]:
# Print the table for the number entered by the user using a while loop
x1 = int(input('Enter a number: '))
i = 1
while(i<=10):
    print(x1, '*', i, '=', x1*i)
    i = i+1

Enter a number: 3
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
3 * 10 = 30


In [27]:
# Count the total no. of digits present in the number entered by the user.
s = int(input('Enter a number: '))
count = 0
while(s!=0):
    s = s//10  # // --> floor division
    count = count+1
print(count)

Enter a number: 41
2


In [28]:
41//10

4

In [30]:
5//10

0

In [2]:
#palindrome
string='Malayalam'


TypeError: string indices must be integers

In [3]:
s="hello"
s[::-1]

'olleh'

In [ ]:
s="hello"


In [5]:
s[:3]

'hel'

In [13]:
s="hello"
s[-2:-5:-1]

'lle'

In [20]:
#palindrome
string='malayalam'
a=string[::-1]
if string==a:
    print('it is palindrome')
else:
    print('it is not palindrome')



it is palindrome


In [37]:
a=10
b=20

In [38]:
c=a
a=b
b=c

In [39]:
print(a,b)

20 10


In [45]:
a=30
b=20 

In [46]:
b,a=a,b

In [47]:
print(a,b)

20 30


In [ ]:
#fibinocci
li=[0 1,1,2,3,5,8,13,21]


In [51]:
n1=0
n2=1
n3=0
print(n1)

print(n2)

for i in range(0,10):
    n3=n1+n2
    n1=n2
    n2=n3
    print(n3)


0
1
1
2
3
5
8
13
21
34
55
89


In [ ]:
#0,1,1,2,3,
#n3=1
#
#n2=1

In [2]:
n1=0
n2=1
n3=0
print(n1)
print(n2)

while n3<=30:
    n3=n1+n2
    n1=n2
    n2=n3
    print(n3)

0
1
1
2
3
5
8
13
21
34


In [1]:
#23-05-23

In [2]:
#class is like blueprint
#object is real time entity by which i can access elements which ar present inside the class
#function and method both are same(func inside the class is called method)

In [3]:
def add(a,b):
    print(a+b)
add(20,30)

50


In [4]:
class A:
    r=12
    def mul(self,x,y):
        print(x+y)
obj=A()
obj.r
obj.mul(2,3)
        

5


In [7]:
class car:
    def wheel(self,price):
        print(price,"is the cost of wheel")
        
    def paint(self,colur):
        print(colur,"is the olour of the car")
        
obj=car()
obj.paint("blue")
        

blue is the olour of the car


In [9]:
#constructir---it is the special method which will be called when an object is created

class A:
    def add(self,a,b):
        print(a+b)
    def __init__(self,w,y):
        print(w+y)
obj=A(4,7)


11


In [10]:
#inheritance--single,multiple,multi-level,hierarchial,hybrid

In [15]:
#single
class A:
    def a1(self):
        print('a1')
class B(A):
    def b1(self):
        print("b1")

obj=B()
obj.b1()
obj.a1()

b1
a1


In [ ]:
#multiple:

In [17]:
#multi-level
class A:
    def a1(self):
        print('a1')
class B(A):
    def b1(self):
        print("b1")
class C(B):
    def c1(self):
        print("c1")

obj=C()
obj.b1()
obj.a1()
obj.c1()

b1
a1
c1


In [23]:
#hierarchial--single parent multiple child
class A:
    def a1(self):
        print('a1')
class B(A):
    def b1(self):
        print("b1")
class C(A):
    def c1(self):
        print("c1")

obj=C()
obj.a1()
obj.c1()

a1
c1


In [25]:
#hybrid 
class A:
    def a1(self):
        print('a1')
        
class D:
    def d1(self):
        print("d1")
        
class B(A,D):
    def b1(self):
        print("b1")
class C(B):
    def c1(self):
        print("c1")
        
class D:
    def d1(self):
        print("d1")
        

obj=B()
obj.a1()
obj.d1()

a1
d1


In [1]:
#06-06-2023

In [2]:
#polymorphism:
#poly means many 
#morphism means many forms


In [3]:
#encapsulation:
#binding of variables

In [4]:
#abstraction:
#hiding the internal things

In [6]:
class a:
    def abc(self):
        print('hello')
        
obj=a() #object of a class is created
obj.abc()

hello


In [8]:
class a:
    def __init__(self):
        print('hey nag')
    def __init__(self):
        print('hey adarsh')
    def abc(self):
        print('hello')
        
obj=a() #object of a class is created
obj.abc()

hey adarsh
hello


In [9]:
#inheritance
#multi-level
class A:
    def a1(self):
        print('a1')
class B(A):
    def b1(self):
        print("b1")
class C(B):
    def c1(self):
        print("c1")

obj=C()
obj.b1()
obj.a1()
obj.c1()

b1
a1
c1


In [23]:
#multiple:father and parent and one child
class A:
    def father(self):
        print('i am father')
class B:
    def mother(self):
        print('i am mother')
class C(A,B):
    def c1(self):
        print("i am your child")
obj=C()
obj.c1()
obj.father()

i am your child
i am father


In [28]:
#hierarchial:single parent multiple child
class A:
    def a1(self):
        print('a1')
class B(A):
    def b1(self):
        print("b1")
class C(A):
    def c1(self):
        print("c1")

obj=C()
obj.c1()

c1


In [25]:
#encapsulation,polymorphism,abstraction--prepare

In [1]:
#encapsulation is like hiding information
#private.protected,public(private__,protected_)
#private means the class can be access with itself
#protected means we can access the data members of one class with other 
#public means it is entirely accessible

In [ ]:
#abstraction that hides the internal implementation details


In [ ]:
#polymorphism--same function name but diffrent functionality
#overloading   operator over loading   method over loading
#over riding    method over riding

In [2]:
1+2

3

In [3]:
"hello "+"amit"

'hello amit'

In [ ]:
#method over loading  --- devoloping multiple methods with the same name but variation in the arguments(parameters)

In [5]:
class A:
    def fun(self,a,b):
        print(a+b)
    def fun(self,x):
        print(x*x)
        
    def fun(self,a,b,c):
        print(a+b+c)
        
obj=A()
obj.fun(2,5,8)

15


In [13]:
#method over riding--devoloping multiple methods with same name in sub class
class A:
    def abc(self,a,b,c):
        print(a+b+c)
class B(A):
    def abc(self,x,y):
        print(x*y)
        super().abc(x,y,c=10)

obj=B()
obj.abc(3,5)

15
18


In [ ]:
#encapsulation--by declaring dat member as private and restricting direct acces outside the class

In [14]:
r=10
__r=10

In [18]:
class A:
    __U=10
    
    def __fun(self):
        print("this is a private function")
        
    def result(self):
        print(self.__U)
        print(self.__fun())
        
obj=A()
obj.result()

10
this is a private function
None


In [19]:
class A:
    __U=10
    
    def __fun(self):
        print("this is a private function")
        
    def __init__(self):
        print(self.__U)
        print(self.__fun())
        
obj=A()

10
this is a private function
None


In [ ]:
#Abstraction
def abc():
    print("heloo")---concret(normal)
    
def xyz():
    passi
    

In [21]:
#from abc import ABC
class A:
    def glow(self):
        pass
    
class B(A):
    def glow(self):
        print("yeahh i got the code")
        
obj=B()
obj.glow()

yeahh i got the code


In [1]:
#20-06-2023

In [2]:
import numpy as np

In [3]:
np.array([1,2])

array([1, 2])

In [4]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [5]:
np.array([[1,2],[3,4],[5,6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
a=np.array([[[1,2],[3,4],[5,6]]])

In [14]:
a

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [12]:
np.ndim(a)

3

In [13]:
a.shape

(1, 3, 2)

In [15]:
#ndim-no of min dim
#ndmin

In [18]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [29]:
np.ndim(newarr)

3

In [6]:
import numpy as np
a = np.arange(1,28).reshape(3,3,3)

In [7]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [5]:
#dtype-specify the datatype for column
#astype--used for changing the datatype

In [14]:
#indexing

In [12]:
a[2][0][1]

20

In [13]:
a[1][1][2]

15

In [24]:
b=np.random.rand(1,20,2)

In [25]:
b

array([[[0.3008058 , 0.47656877],
        [0.35389302, 0.06570183],
        [0.79433784, 0.44532497],
        [0.17697058, 0.01370326],
        [0.94647616, 0.29153397],
        [0.51974751, 0.64940776],
        [0.44522448, 0.80318851],
        [0.3832998 , 0.01317909],
        [0.4486239 , 0.13858756],
        [0.03988021, 0.80966865],
        [0.56410825, 0.96537497],
        [0.37554642, 0.08588077],
        [0.64895246, 0.38266635],
        [0.44622662, 0.3430967 ],
        [0.4644211 , 0.65158877],
        [0.72423582, 0.35644541],
        [0.57063406, 0.45081654],
        [0.40451895, 0.46298831],
        [0.05709704, 0.70531853],
        [0.72727952, 0.39429081]]])

In [26]:
a[2][2][0]

25

In [31]:
import pandas as pd
d = {'SNo': [1, 2], 'Name': ['nag', 'ashwin']}
df = pd.DataFrame(data=d)
df

SNo    Name
0    1     nag
1    2  ashwin

In [34]:
df.dtypes

SNo      int64
Name    object
dtype: object

In [44]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
a.dtype

dtype('int32')

In [49]:
a.astype('float')

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [51]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [54]:
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [57]:
np.transpose(a)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [58]:
np.linspace(start=5,stop=25,num=3,dtype=int)

array([ 5, 15, 25])

In [59]:
np.logspace(start=5,stop=20,num=6)

array([1.e+05, 1.e+08, 1.e+11, 1.e+14, 1.e+17, 1.e+20])

In [62]:
np.linspace(5,10,3,dtype=float)

array([ 5. ,  7.5, 10. ])

In [63]:
np.linspace(5,10,dtype=float)

array([ 5.        ,  5.10204082,  5.20408163,  5.30612245,  5.40816327,
        5.51020408,  5.6122449 ,  5.71428571,  5.81632653,  5.91836735,
        6.02040816,  6.12244898,  6.2244898 ,  6.32653061,  6.42857143,
        6.53061224,  6.63265306,  6.73469388,  6.83673469,  6.93877551,
        7.04081633,  7.14285714,  7.24489796,  7.34693878,  7.44897959,
        7.55102041,  7.65306122,  7.75510204,  7.85714286,  7.95918367,
        8.06122449,  8.16326531,  8.26530612,  8.36734694,  8.46938776,
        8.57142857,  8.67346939,  8.7755102 ,  8.87755102,  8.97959184,
        9.08163265,  9.18367347,  9.28571429,  9.3877551 ,  9.48979592,
        9.59183673,  9.69387755,  9.79591837,  9.89795918, 10.        ])

In [70]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [72]:
np.eye(4,3,k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [77]:
a=np.arange(1,4)

In [78]:
b=np.arange(4,7)

In [84]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [85]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
np.dstack((a,b))

array([[[1, 4],
        [2, 5],
        [3, 6]]])